### ISSUE TITLE
Code highlighter doesn't work

### ISSUE THREAD

**Issue by Puzer** [SofianHamiti/amazon-sagemaker-notebook-instance-lifecycle-config-theia#1]
Hi Sofian, thank you for your work, right in time for me :)

I tried to install extension [ms-python/python](https://open-vsx.org/extension/ms-python/python) on top of your codebase, but seems that IntelSense, autocomplition of code etc doesn't work.
![image](https://user-images.githubusercontent.com/1623268/107162521-d136ee80-69b4-11eb-8337-a844db29e68a.png)

Initially I tried to install it manually and also tried to modify [package.json](https://github.com/Puzer/amazon-sagemaker-notebook-instance-lifecycle-config-theia/blob/update/config/package.json#L85) to install it automatically, but unsuccessfully.

I'm not an advanced user of Theia or even VSCode, sorry for dumb questions :)

**Comment by sofianhamiti** [comment]
Hi Dimitri, yes Theia has recently been updated and it seems like it broke the python interpreter. Let me do some debugging and come back to you on this.

**Comment by sofianhamiti** [comment]
Hi Dimitri, apologies for the late response.

This Theia approach has been fairly challenging to work with and maintain over time.

[Hosting VSCode on SageMaker Studio](https://towardsdatascience.com/hosting-vs-code-in-sagemaker-studio-f211385e25f7) should be a better for you the long term, as it installs proper VSCode and has larger community.
